// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1a7c9917-ecda-4b66-9aa0-3bca34892f3d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uUgoxvEf7",
    "aws_user_pools_web_client_id": "3oer5t7qdbopdqi3c9a9hpgp5s",
    "aws_appsync_graphqlEndpoint": "https://5lipwd4x2bdmbkev3bjxlzzoje.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
